// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmcsefdlsbynxkufpql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bWNzZWZkbHNieW54a3VmcHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTEwMzQsImV4cCI6MjA1NTc4NzAzNH0.5wQF8SkNF-yMhkKFPOYEkzo3zj5cDariFEa-rGRIkRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);